package org.sang.model;

public class ArticleWithBLOBs extends Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.content
	 * @mbg.generated  Tue Nov 07 16:00:47 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.summary
	 * @mbg.generated  Tue Nov 07 16:00:47 CST 2017
	 */
	private String summary;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.content
	 * @return  the value of article.content
	 * @mbg.generated  Tue Nov 07 16:00:47 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.content
	 * @param content  the value for article.content
	 * @mbg.generated  Tue Nov 07 16:00:47 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.summary
	 * @return  the value of article.summary
	 * @mbg.generated  Tue Nov 07 16:00:47 CST 2017
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.summary
	 * @param summary  the value for article.summary
	 * @mbg.generated  Tue Nov 07 16:00:47 CST 2017
	 */
	public void setSummary(String summary) {
		this.summary = summary;
	}
}