package org.sang.model;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_id
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comm_ip
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    private String commIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_id
     *
     * @return the value of comments.article_id
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_id
     *
     * @param articleId the value for comments.article_id
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comm_ip
     *
     * @return the value of comments.comm_ip
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    public String getCommIp() {
        return commIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comm_ip
     *
     * @param commIp the value for comments.comm_ip
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    public void setCommIp(String commIp) {
        this.commIp = commIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment
     *
     * @return the value of comments.comment
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment
     *
     * @param comment the value for comments.comment
     *
     * @mbg.generated Tue Oct 31 12:00:16 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}